# .github/workflows/deploy_workflow.yaml
name: Despliegue de la aplicación

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      env_name:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.env_name }}
    steps:

      - name: show env
        run: |
          echo "Este es el entorno ${{ inputs.env_name }}"

      - name: Pull image
        run: |
          docker pull ${{ inputs.image_name }}

      - name: Run container
        run: |
          docker run -d -p 8080:8080 --name github-weekly ${{ inputs.image_name }}

      - name: Show containers
        run: |
          docker ps 

      - name: Verificación del funcionamiento de la app
        run: |
          curl http://localhost:8080
