
name: Despliegue de la aplicación

on:
  workflow_call:
jobs:
  
  build:
    runs-on: ubuntu-latest
    environment: production
    env: 
      DOCKER_USER: ${{ secrets.DOCKERHUB_USER }}
    # Instalar docker
    steps:
      - name: Pull image
        run: |
          docker pull $DOCKER_USER/sample-angular-app:0.0.0
      - name: upload container
        run: |
          docker run -d -p 8080:8080 --name github-weekly $DOCKER_USER/sample-angular-app:0.0.0
      - name: Show containers
        run: |
          docker ps 
      - name: Verificación del funcionamiento de la app
        run: |
          curl http://localhost:8080
          

      
     

      
          
