name: Construcción y Despliegue de App

on:
  push:
    branches:
      - main
      - develop

jobs:
  call_workflow_CI: 
    uses: ./.github/workflows/ci_workflow.yaml
    secrets: inherit
    with:
      environment: production

  call_workflow_CD: 
    needs: call_workflow_CI
    uses: ./.github/workflows/cd_workflow.yaml
    secrets: inherit
    with:
        image_name: ${{ needs.call_workflow_CI.outputs.image_name }}
        environment: production
    
