name: Construcción y Despliegue de App

on:
  push:
    branches:
      - main
      - develop

jobs:

  set_environment:
    outputs:
      env_name: ${{ steps.set_env.outputs.env_name }}
    runs-on: ubuntu-latest
    steps:
      - id: get_branch
        name: Obtener el nombre de la rama donde se está realizando la acción
        run: |
          echo "BRANCH_NAME=$(basename $GITHUB_REF)" >> $GITHUB_OUTPUT

      - id: set_env
        name: Setear el valor del environment en función de la rama donde se realiza la acción
        run: |
          if [ "${{ steps.get_branch.outputs.BRANCH_NAME }}" == "main" ]; then
            echo "env_name=production" >> $GITHUB_OUTPUT
          elif [ "${{ steps.get_branch.outputs.BRANCH_NAME }}" == "develop" ]; then
            echo "env_name=UAT" >> $GITHUB_OUTPUT
          fi


 
  call_workflow_CI: 
    needs: set_environment
    uses: ./.github/workflows/ci_workflow.yaml
    secrets: inherit
    with:
      environment: ${{ needs.set_environment.outputs.env_name }}

  # call_workflow_CD: 
  #   needs: call_workflow_CI
  #   uses: ./.github/workflows/cd_workflow.yaml
  #   secrets: inherit
  #   with:
  #       image_name: ${{ needs.call_workflow_CI.outputs.image_name }}
  #       environment: ${{ needs.set_environment.outputs.env_name }}
    
