name: Construcción y Despliegue de App

on:
  workflow_dispatch:

jobs:

  set_environment:
    outputs:
      ENV_NAME: ${{ steps.set_env.outputs.env_name }}
      BRANCH_NAME: ${{ steps.get_branch.outputs.BRANCH_NAME }}
    runs-on: ubuntu-latest
    steps:
      - id: get_branch
        name: Obtener el nombre de la rama donde se está realizando la acción
        run: |
          echo "BRANCH_NAME=$(basename $GITHUB_REF)" >> $GITHUB_OUTPUT

      - id: set_env
        name: Setear el valor del environment en función de la rama donde se realiza la acción
        run: |
          if [ "${{ steps.get_branch.outputs.BRANCH_NAME }}" = "main" ]; then
            echo "ENV_NAME=production" >> $GITHUB_OUTPUT
          elif [ "${{ steps.get_branch.outputs.BRANCH_NAME }}" = "develop" ]; then
            echo "ENV_NAME=UAT" >> $GITHUB_OUTPUT
          fi




 
  # show_env: 
  #   needs: set_environment
  #   uses: ./.github/workflows/show_env.yaml
  #   secrets: inherit
  #   with:
  #     environment: ${{ needs.set_environment.outputs.ENV_NAME }}
  #     branch_name: ${{ needs.set_environment.outputs.BRANCH_NAME }}
  call_workflow_CI: 
    needs: set_environment
    uses: ./.github/workflows/ci_workflow.yaml
    secrets: inherit
    with:
      env_name: ${{ needs.set_environment.outputs.ENV_NAME }}
      branch_name: ${{ needs.set_environment.outputs.BRANCH_NAME }}

  call_workflow_CD: 
    needs: call_workflow_CI
    uses: ./.github/workflows/cd_workflow.yaml
    secrets: inherit
    with:
        image_name: ${{ needs.call_workflow_CI.outputs.image_name }}
        env_name: ${{ needs.set_environment.outputs.ENV_NAME }}
    
