name: Contrucción y despliegue de app

on:
  workflow_dispatch:

jobs:
# Extraemos el nombre de la imagen para usarla en los dos reusables
  call_image_name_generator:
    uses: ./.github/workflows/image_name_generator.yaml
    secrets: inherit
    
  main_task:
    needs: call_image_name_generator
    runs-on: ubuntu-latest  
    steps:
      - name: MOstrar mensaje para tarea principal
        run: |
          echo "El nombre de la imagen es ${{ needs.call_image_name_generator.outputs.image_final_name }}"
#   call_workflow_CI:
#     uses: ./.github/workflows/ci_workflow.yaml
#     secrets: inherit
#   call_workflow_CD:
#     needs: call_workflow_CI
#     uses: ./.github/workflows/cd_workflow.yaml
#     secrets: inherit
