name: Creación y subida de la imagen de angular
on:
  workflow_call:
jobs:
  build:
    runs-on: ubuntu-latest
    # outputs:
    #   image_final_name:
    #     description: Nombre de la imagen
    #     value: ${{ steps.value_setter.outputs.image_name }}
    # environment: production
   
    # Instalar docker
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Mostrando las variables
        run: |
          echo ${{ vars.DOCKERHUB_USER }}
          echo ${{ secrets.DOCKERHUB_PASS }}

      # Llamar a la action que me crea el nombre de la imagen
      - name: Extractor de la versión de un fichero JSON
        id: version_extractor
        uses: ./.github/actions/extractor
        with:
          file_path: ${{ vars.PACKAGE_JSON_PATH }}
          field_name: version
          
      - name: Extractor del nombre de un fichero JSON
        id: name_extractor
        uses: ./.github/actions/extractor
        with:
          file_path: ${{ vars.PACKAGE_JSON_PATH }}
          field_name: name
          
      - name: Llamar a la action que me crea el nombre de la imagen
        id: tagger
        uses: ./.github/actions/tagger_action
        with:
          user_name: ${{ vars.DOCKERHUB_USER }}
          app_name: ${{ steps.name_extractor.outputs.field_value }}
          app_version: ${{ steps.version_extractor.outputs.field_value }}
          
      # Mostrar el nombre de la imagen creada
      - name: Mostrando el nombre de la imagen
        id: value_setter
        run: |
          echo "The output from the action is: ${{ steps.tagger.outputs.image_name }}"
          echo "image_final_name=${{ steps.tagger.outputs.image_name }}" >> $GITHUB_OUTPUT
      - name: Mostrando las variables
        run: |
          echo "Esta es la variable del paso anterior ${{ steps.value_setter.ouputs.image_final_name }}"
   
      
