name: Extracción del nombre de la imagen
on:
  workflow_call:
    outputs:
      image_final_name:
        description: "Nombre final de la imagen"
        value: ''

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Llamar a la action que me crea el nombre de la imagen
      - name: Extractor de la versión de un fichero JSON
        id: version_extractor
        uses: ./.github/actions/extractor
        with:
          file_path: ${{ vars.PACKAGE_JSON_PATH }}
          field_name: version

      - name: Extractor del nombre de un fichero JSON
        id: name_extractor
        uses: ./.github/actions/extractor
        with:
          file_path: ${{ vars.PACKAGE_JSON_PATH }}
          field_name: name

      - name: Llamar a la action que me crea el nombre de la imagen
        id: tagger
        uses: ./.github/actions/tagger_action
        with:
          user_name: ${{ vars.DOCKERHUB_USER }}
          app_name: ${{ steps.name_extractor.outputs.field_value }}
          app_version: ${{ steps.version_extractor.outputs.field_value }}

      # Establecer la salida del trabajo como un valor simple
      - name: Establecer salida del nombre de la imagen
        id: output_setter
        run: |
          echo "image_final_name=${{ steps.tagger.outputs.image_name }}" >> $GITHUB_OUTPUT
