name: Construcción y Despliegue de App

on:
  workflow_call:
    inputs:
      environment:
        description: Valor para el entorno que se va a usar
        required: true
        type: string

jobs:
  show:
    environment: ${{ inputs.environment}}
    runs-on: ubuntu-latest
    steps:
      - name: show 
        run: |
          echo "Este es el nombre del usuario $ {{ vars.DOCKERHUB_USER }}"
      
